CREATE TABLE `rpg`.`characters` (
  `cid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `p_c_id` VARCHAR(45) NOT NULL,
  `level` SMALLINT NOT NULL DEFAULT 1,
  `weapon` SMALLINT NULL DEFAULT NULL,
  `helmet` SMALLINT NULL DEFAULT NULL,
  `chestplate` SMALLINT NULL DEFAULT NULL,
  `leggings` SMALLINT NULL DEFAULT NULL,
  `boots` SMALLINT NULL DEFAULT NULL,
  `necklace` SMALLINT NULL DEFAULT NULL,
  `ring` SMALLINT NULL DEFAULT NULL,
  `any` SMALLINT NULL DEFAULT NULL,
  `owner_id` INT UNSIGNED NOT NULL,
  `skill1` VARCHAR(45) NULL DEFAULT NULL,
  `skill2` VARCHAR(45) NULL DEFAULT NULL,
  `skill3` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`cid`),
  UNIQUE INDEX `cid_UNIQUE` (`cid` ASC) VISIBLE,
  INDEX `uid_idx` (`owner_id` ASC) VISIBLE,
  CONSTRAINT `character_owner_id`
    FOREIGN KEY (`owner_id`)
    REFERENCES `rpg`.`users` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);